Update and rename pure to pu

diff --git a/pu b/pu
--- a/pu
+++ b/pu
@@ -20,16 +20,12 @@ clear
 read -rp "Enter your OBFS: " -e OBFS
 clear
 
-# PASSWORDS
-read -rp "Enter your PASSWORD: " -e PASSWORD
-clear
-
 
 # PROTOCOL
 PROTOCOL="udp"
 
 # UDP PORT
-UDP_PORT=":5666"
+UDP_PORT="5666"
 
 # Basename of this script
 SCRIPT_NAME="$(basename "$0")"
@@ -678,24 +674,70 @@ tpl_hysteria_server_x_service() {
 
 # /etc/hysteria/config.json
 tpl_etc_hysteria_config_json() {
+
+cat <<\EOM >/etc/hysteria/config.sh
+#!/bin/bash
+HOST='185.61.137.171'
+USER='mediatek2_getorssh'
+PASS='F1005r90@'
+DB='mediatek2_getorssh'
+EOM
+
+
   cat << EOF
 {
-  "listen": "$UDP_PORT",
+  "listen": ":$UDP_PORT",
   "protocol": "$PROTOCOL",
   "cert": "/etc/hysteria/hysteria.server.crt",
   "key": "/etc/hysteria/hysteria.server.key",
-  "up": "100 Mbps",
   "up_mbps": 100,
-  "down": "100 Mbps",
   "down_mbps": 100,
   "disable_udp": false,
   "obfs": "$OBFS",
   "auth": {
-	"mode": "passwords",
-	"config": ["$PASSWORD"]
-         }
+    "mode": "external",
+    "config": {
+    "cmd": "./.auth.sh"
+  }
 }
 EOF
+
+
+cat <<"EOM" >/etc/hysteria/.auth.sh
+#!/bin/bash
+. /etc/hysteria/config.sh
+
+if [ $# -ne 4 ]; then
+    echo "invalid number of arguments"
+    exit 1
+fi
+
+ADDR=$1
+AUTH=$2
+SEND=$3
+RECV=$4
+
+USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
+PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
+
+USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
+PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
+
+Query="SELECT user_name FROM users WHERE user_name='$USERNAME' AND auth_vpn=md5('$PASSWORD') AND status='live' AND is_freeze=0 AND is_ban=0 AND (duration > 0 OR vip_duration > 0 OR private_duration > 0)"
+user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
+[ "$user_name" != '' ] && [ "$user_name" = "$USERNAME" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
+EOM
+
+
+chmod 755 /etc/hysteria/.auth.sh
+
+sysctl -w net.core.rmem_max=16777216
+sysctl -w net.core.wmem_max=16777216
+
+wget -O /usr/bin/badvpn-udpgw "https://apk.admin-boyes.com/setup/badvpn-udpgw64"
+chmod +x /usr/bin/badvpn-udpgw
+ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /usr/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 10 --client-socket-sndbuf 10000
+
 }
 
 
@@ -1021,7 +1063,7 @@ start_services() {
 	echo "Starting AGN-UDP"
 	apt update
 	sudo debconf-set-selections <<< "iptables-persistent iptables-persistent/autosave_v4 boolean true"
-        sudo debconf-set-selections <<< "iptables-persistent iptables-persistent/autosave_v6 boolean true"
+    sudo debconf-set-selections <<< "iptables-persistent iptables-persistent/autosave_v6 boolean true"
 	apt -y install iptables-persistent
 	iptables -t nat -A PREROUTING -i $(ip -4 route ls|grep default|grep -Po '(?<=dev )(\S+)'|head -1) -p udp --dport 20000:65000 -j DNAT --to-destination $UDP_PORT
 	ip6tables -t nat -A PREROUTING -i $(ip -4 route ls|grep default|grep -Po '(?<=dev )(\S+)'|head -1) -p udp --dport 20000:65000 -j DNAT --to-destination $UDP_PORT
@@ -1031,8 +1073,8 @@ start_services() {
 	net.ipv4.conf.all.rp_filter=0
 	net.ipv4.conf.$(ip -4 route ls|grep default|grep -Po '(?<=dev )(\S+)'|head -1).rp_filter=0" > /etc/sysctl.conf  
 	sysctl -p
-        sudo iptables-save > /etc/iptables/rules.v4
-        sudo ip6tables-save > /etc/iptables/rules.v6
+    sudo iptables-save > /etc/iptables/rules.v4
+    sudo ip6tables-save > /etc/iptables/rules.v6
 	systemctl enable hysteria-server.service
 	systemctl start hysteria-server.service	
 }
